services:

  h2-database-java21:
    build: ./docker/java-21
    ports:
      - '9092:9092'
      - '5435:5435'
      - '8082:8082'
    volumes:
      - ./data/h2/logs:/usr/workspace/logs
      - ./data/h2/data:/usr/workspace/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
